version: "3.9"

services:
  microsoft_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - lend

  microsoft_pgadmin:
    image: dcagatay/pwless-pgadmin4:6.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: microsoft_db
    ports:
      - "8080:80"
    depends_on:
      - microsoft_db
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - microsoft

networks:
  microsoft:
    driver: bridge
