name: Main

on:
  push:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/step-tests-python.yml
    secrets: inherit
  docker:
    needs: tests
    uses: ./.github/workflows/step-docker-build-push.yml
    secrets: inherit
