name: Tests Python

on:
  workflow_call:

jobs:
  tests:
    name: python
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate YAML file
        run: "yamllint --list-files -d '{extends: relaxed, rules: {line-length: {max: 200}, new-line-at-end-of-file: false, trailing-spaces: false}}' ./"

      - name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Check code"
        run: |
          make format
      
      - name: "Run tests and check coverage"
        run: |
          make coverage
      
      - name: "Run unit tests"
        run: |
          make unit-test

      - name: "Run integration tests"
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          make integration-test