name: Tests Python

on:
  workflow_call:

jobs:
  tests:
    name: python
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate YAML file
        run: "yamllint --list-files -d '{extends: relaxed, rules: {line-length: {max: 200}, new-line-at-end-of-file: false, trailing-spaces: false}}' ./"

      - name: Validate YAML ConfigMaps
        run: bash ./bin/validate-env-configmaps.sh

      - name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Check code"
        run: |
          make format

      - name: "Run tests and check coverage"
        run: |
          make coverage

      - name: "Run integration tests"
        run: |
          make integration-test