name: Docker Build&Push

on:
  workflow_call:

jobs:
  docker:
    name: build&push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Prepare private dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-txt
